services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://localhost:11434
      - MODEL_NAME=mistral
      - DATABASE_URL=postgresql://postgres:09123@db:5432/dataextract
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=09123
      - POSTGRES_DB=dataextract
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: